
---
title: "Visualisation of COVID-19 and video presence"
author: "Tuesday Group F"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


```{r include=FALSE}
# General chunk options (applied to all subsequent chunks):

knitr::opts_chunk$set(
  # echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```


```{r}
# Load libraries:
# install.packages('tidyverse')
library(tidyverse)
library(httr)
library(readxl)
library(lubridate)
library(tsibble)
library(forcats)
library(plotly)
library(ggridges)
library(janitor)

```

## Introduction

## Part 1: Get the data

### load People

```{r}
#TODO Task-B
```

### load video information

```{r}
videos <- read_csv("data/videos.csv") %>% janitor::clean_names()
glimpse(videos)
```

## Part 2: Prepare the data

Extract date and convert to date format
```{r}
videos <- videos %>% 
  mutate(video_date=
           dmy(str_extract(title,pattern="[0-9][0-9]\\.[0-9][0-9]\\.[0-9][0-9][0-9][0-9]")))

videos %>% select(video_date)
```

#### join data

```{r}

```

TODO Ling covid data to video

